export const demoPresets = {
  fashion: {
    storeName: "Maison Atelier",
    tagline: "Editorial fashion pieces for modern wardrobes.",
    primaryColor: "#7B3F61",
    secondaryColor: "#E9C46A",
    accentColor: "#1F1F1F",
    bgPrimary: "#F7F1F4",
    bgSecondary: "#F5E8EB",
    surfaceColor: "#FFFFFF",
    surfaceSoftColor: "#F4EDF0",
    navbarBackground: "#1F1F1F",
    footerBackground: "#111111",
    headingColor: "#1F1F1F",
    bodyTextColor: "#3A3A3A",
    mutedTextColor: "#716070",
    borderColor: "#D8C2CF",
    successColor: "#22C55E",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#3B82F6",
    heroTitle: "Client-ready fashion storefront",
    heroSubtitle: "Elegant storytelling, curated arrivals, and a premium checkout flow.",
  },
  electronics: {
    storeName: "Volt Edge",
    tagline: "Smart devices, fast delivery, clean shopping experience.",
    primaryColor: "#0F4C81",
    secondaryColor: "#56CFE1",
    accentColor: "#111827",
    bgPrimary: "#F3F7FB",
    bgSecondary: "#E9F2FB",
    surfaceColor: "#FFFFFF",
    surfaceSoftColor: "#EDF4FB",
    navbarBackground: "#111827",
    footerBackground: "#0F172A",
    headingColor: "#0F172A",
    bodyTextColor: "#334155",
    mutedTextColor: "#64748B",
    borderColor: "#CBD5E1",
    successColor: "#10B981",
    warningColor: "#F59E0B",
    dangerColor: "#EF4444",
    infoColor: "#38BDF8",
    heroTitle: "High-converting electronics template",
    heroSubtitle: "Built for specs, variants, shipping clarity, and trusted checkout.",
  },
  beauty: {
    storeName: "Lune Beauty",
    tagline: "Glow-focused essentials with a refined premium feel.",
    primaryColor: "#C06C84",
    secondaryColor: "#F8B195",
    accentColor: "#355C7D",
    bgPrimary: "#FEF7F8",
    bgSecondary: "#FFF1F4",
    surfaceColor: "#FFFFFF",
    surfaceSoftColor: "#FFF4F6",
    navbarBackground: "#2B3752",
    footerBackground: "#1F243A",
    headingColor: "#1F2937",
    bodyTextColor: "#4B5563",
    mutedTextColor: "#6B7280",
    borderColor: "#E5E7EB",
    successColor: "#22C55E",
    warningColor: "#F59E0B",
    dangerColor: "#DC2626",
    infoColor: "#2563EB",
    heroTitle: "Beauty store demo for fast client launch",
    heroSubtitle: "Soft branding, persuasive product storytelling, and polished merchandising.",
  },
};

export default demoPresets;
