name: Keep Render Backend Alive
on:
     schedule:
       - cron: '*/10 * * * *'
     workflow_dispatch:

   jobs:
     ping:
       runs-on: ubuntu-latest
       steps:
         - name: Ping backend
           run: curl -s https://e-commerce-project-r86z.onrender.com
